sub_odom_topic_name: /odometry/filtered
sub_pitot_topic_name: /droni_sensors/pitot_pressure
sub_accel_topic_name: /droni_sensors/angular_accel_filtered
pub_estimated_wind_topic_name: /wind_speed/filtered_ekf
process_covariance: [1.0e-3, 1.0e-3, 5.0e-6]
measurement_covariance: [655.0, 655.0, 655.0]
initial_covariance: [0.09, 0.09, 1.0e-8]
initial_state: [0.0,-2.0,0.74]
lambda_rdot: 100.0